apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azurestatichosts.asterius.fr
spec:
  group: asterius.fr
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                host:
                  type: string
                source:
                  type: object
                  properties:
                    host:
                      type: string
                    path:
                      type: string
                      default: ""
                  required:
                    - host
              required:
                - host
                - source
  scope: Namespaced
  names:
    plural: azurestatichosts
    singular: azurestatichost
    kind: AzureStaticHost
    shortNames:
      - azhost