name: Push Helm Chart to Scaleway

on:
  push:
    tags:
      - "*"

env:
  CHART_PATH: ./stp-operator
  REGISTRY: rg.fr-par.scw.cloud
  NAMESPACE: asterius-public-helm/operators

jobs:
  push-helm-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Extract tag name
        id: tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Package Helm chart
        run: helm package ${{ env.CHART_PATH }} --version ${{ steps.tag.outputs.TAG }}

      - name: Push Helm chart
        run: |
          helm registry login ${{ env.REGISTRY }} --username=${{ secrets.SCW_ACCESS_KEY }} --password=${{ secrets.SCW_SECRET_KEY }}
          helm push *.tgz oci://${{ env.REGISTRY }}/${{ env.NAMESPACE }}
